/**
 * Reads version from package.json and writes src/version.ts.
 * Run automatically via "prebuild" script before tsc.
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(resolve(__dirname, '../package.json'), 'utf-8'));

const content = `// Auto-generated by scripts/generate-version.mjs — do not edit manually
export const VERSION = '${pkg.version}';
`;

const outPath = resolve(__dirname, '../src/version.ts');
writeFileSync(outPath, content, 'utf-8');
console.log(`[generate-version] src/version.ts → ${pkg.version}`);
